[features]
seeds = false
[programs.localnet]
solana-2048 = "2o48YSS8GdsvXk9qWXsoctcHdLkEfkmkTeaggXtaVJzX"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "/Users/jonasmac2/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
